server.port: 8080

spring:
  application:
    name: BuildStitch-monolith

  datasource:
    url: jdbc:postgresql://localhost:5432/BuildStitchDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt.secret-key: thisIsMySecretKey21082026buildstitch